name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.2", "8.3", "8.4"]
        include:
          - php-version: "8.2"
            stable: true
          - php-version: "8.3"
            stable: true
          - php-version: "8.4"
            stable: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/php
          tags: |
            type=semver,pattern={{version}}-php${{ matrix.php-version }}
            type=ref,event=branch,enable=${{ github.ref == 'refs/heads/main' }},suffix=-php${{ matrix.php-version }}
            type=raw,value=latest-php${{ matrix.php-version }},enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=${{ matrix.php-version }},enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./php-${{ matrix.php-version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=php-${{ matrix.php-version }}
          cache-to: type=gha,scope=php-${{ matrix.php-version }},mode=max
          platforms: linux/amd64,linux/arm64